AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  clcustomerPortaluploadima2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::332124071547:role/service-role/cl-customerPortal-uploadima2-role-ngyo1dl3
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /uploadimage
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api3:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        Api4:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
