AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  clcustomerPortalnewCustomersaveData:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::332124071547:role/service-role/cl-customerPortal-newCustomer-saveData-role-ozv3baoc
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /createnewcustomer
            Method: POST
