AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  clcustomerPortalsignUpcustomerValidation:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::332124071547:role/service-role/cl-customerPortal-signUp-customerValidation-role-kf7x0s0t
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /signup/validation
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      Layers:
        - 'arn:aws:lambda:us-east-1:332124071547:layer:Axios:1'
