AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  clcustomerPortalordersList:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: >-
        arn:aws:iam::332124071547:role/service-role/cl-customerPortal-ordersList-role-znf6z6n7
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /orders
            Method: GET
